### ISSUE TITLE
ask: Integral untuk mencari volume dari Hidrograf Banjir

### ISSUE THREAD

**Issue by Saepool** [taruma/hidrokit#52]
### Permintaan fitur/ide

Bantu buatkan integral untuk mencari volume dari Hidrograf Banjir

**Comment by taruma** [comment]
Terima kasih atas idenya @Saepool.

Kemungkinan saya utak-atik dulu di Google colab/jupyter notebook, mungkin kalau hidrokit 0.2.0 dah rilis, baru saya integrasikan.

**Comment by Saepool** [comment]
Baik ty

**Comment by taruma** [comment]
Ini bisa diselesaikan dengan fungsi numpy.trapz (menghitung luas integral menggunakan metode trapesium).

contohnya:
- https://nbviewer.jupyter.org/gist/taruma/d763d303f5a4e753caebaa3dcb0e7726

**Comment by Saepool** [comment]
Oke
Nuhun Kang

Pada tanggal Rab, 3 Jul 2019 11.25 AM, Taruma Megariansyah <
notifications@github.com> menulis:

**Comment by taruma** [comment]
ditutup karena akhir pengembangan dari saya.
