### ISSUE TITLE
ask: Menentukan kriteria berdasarkan total nilai bulanan

### ISSUE THREAD

**Issue by dickymuhamadf** [taruma/hidrokit#60]
### Ringkasan
ini mau buat data kriteria harian berdasarkan kriteria bulanan.
contohnya 
![image](https://user-images.githubusercontent.com/36441632/61350123-acd66700-a890-11e9-8548-f65a1881f031.png)
nah data kriteria tadi mau diisi berdasarkan data kriteria bulanan itu

**Comment by taruma** [comment]
Hai @dickymuhamadf,

Saya coba rekap permasalahannya:
- Saya memiliki dataset harian nilai a, b, c selama X tahun.
- Saya ingin mengkategorikan nilai di kolom a, berdasarkan nilai total bulanan-nya.
- Hasil pengategorian tersebut dibuat pada kolom baru bernama 'kategori'.

Saya sudah coba solusinya menggunakan python. Berikut solusinya: https://gist.github.com/taruma/2a33a8877ebc79ad16e0aed21c35e0ca

Kalau untuk excel, langkah yang saya terpikirkan adalah:
- Buat tabel pivot yang meringkas hasil bulanannya.
- Buat kolom dengan hasil total bulanannya.
- Buat kolom kategori dengan kondisi IF.

**Comment by taruma** [comment]
ditutup karena akhir pengembangan dari saya.
